name: Build & Deploy

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'


jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Install dependencies
        run: pip install -r requirements.txt
        
      - name: Unit tests
        run: python -m unittest discover

      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: fiitteam8/news_scraper
          tags: v1, latest
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
